name: Cluster Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "nightly"
          - "v1.2.790-nightly"
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Start Cluster With Nginx and Minio
        working-directory: tests
        run: make up
        env:
          DATABEND_QUERY_VERSION: ${{ matrix.version }}

      - name: Test with conn to nginx
        run: mvn test -DexcludedGroups=FLAKY
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          DATABEND_TEST_CONN_PORT: 8000
          DATABEND_QUERY_VERSION: ${{ matrix.version }}
