name: Compatibility Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server:
          - "nightly"
          - "v1.2.790-nightly"
        driver:
          - "0.4.0"
          - "0.3.9"
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Start Cluster With Nginx and Minio
        working-directory: tests
        run: make up
        env:
          DATABEND_QUERY_VERSION: ${{ matrix.server }}

      - name: Set Release version env variable
        run: |
          echo "DATABEND_TEST_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Test with conn to nginx
        working-directory: tests/compatibility
        run: sh test_compatibility.sh
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          DATABEND_TEST_CONN_PORT: 8000
          DATABEND_QUERY_VERSION: ${{ matrix.server }}
          DATABEND_JDBC_VERSION: ${{ matrix.driver }}
          TEST_SIDE: "driver"
